process:
  #raw_data_file_path: "data/Friends_script.csv"
  raw_data_file_path: "data/Friends_script_short.csv"
  script_with_line_embeddings_path: "data/Friends_script_embeddings.parquet"
  num_sequences: 50
  max_context_length: 10
  main_characters: [
    "Ross",
    "Phoebe",
    "Rachel",
    "Joey",
    "Chandler",
    "Monica"
  ]

embedding:
  # model_name: "Qwen/Qwen3-Embedding-8B"
  model_name: "Qwen/Qwen3-Embedding-0.6B"
  # dimension: 4096
  dimension: 1024
  batch_size: 10

train:
  train_file: "data/train.parquet"
  val_file: "data/val.parquet"
  test_file: "data/test.parquet"
  num_layers: 2
  batch_size: 4
  num_heads: 4
  dropout: 0.2
  scheduler_mode: "min"
  scheduler_factor: 0.5
  scheduler_patience: 2
  learning_rate: 0.001
  weight_decay: 0.00001
  epochs: 50
  patience: 5
  running_train_loss_steps: 100
  

