process:
  file: "data/Friends_script.csv"
  num_sequences: 10
  max_context_length: 5
  output: "data/processed_data.parquet"

train:
  train_file: "data/processed_data_train.parquet"
  val_file: "data/processed_data_val.parquet"
