process:
  raw_data_file_path: "data/Friends_script.csv"
  num_sequences: 50_000
  max_context_length: 10
  main_characters: [
    "Ross",
    "Phoebe",
    "Rachel",
    "Joey",
    "Chandler",
    "Monica"
  ]

embeddings:
  model_url: "http://localhost:8081"
  dimension: 4096
  batch_size: 10

train:
  train_file: "data/train_*.parquet"
  val_file: "data/val_*.parquet"
  max_files: 10_000
  num_heads: 4
  dropout: 0.2
  scheduler_mode: "min"
  scheduler_factor: 0.5
  scheduler_patience: 2
  batch_size: 4
  learning_rate: 0.001
  weight_decay: 0.00001
  epochs: 50
  patience: 5


